export const categories = [
  {
    id: "1",
    name: "Electronics",
    slug: "electronics",
    subCategory: [
      {
        id: "101",
        name: "Mobile Phones",
        slug: "mobile-phones",
        categoryId: "1",
        subCategory: [
          {
            id: "1011",
            name: "Smartphones",
            slug: "smartphones",
            categoryId: "101",
          },
          {
            id: "1012",
            name: "Feature Phones",
            slug: "feature-phones",
            categoryId: "101",
          },
        ],
      },
      {
        id: "102",
        name: "Laptops",
        slug: "laptops",
        categoryId: "1",
        subCategory: [
          {
            id: "1021",
            name: "Gaming Laptops",
            slug: "gaming-laptops",
            categoryId: "102",
          },
          {
            id: "1022",
            name: "Business Laptops",
            slug: "business-laptops",
            categoryId: "102",
          },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Fashion",
    slug: "fashion",
    subCategory: [
      {
        id: "201",
        name: "Men's Clothing",
        slug: "mens-clothing",
        categoryId: "2",
        subCategory: [
          { id: "2011", name: "Shirts", slug: "shirts", categoryId: "201" },
          { id: "2012", name: "Pants", slug: "pants", categoryId: "201" },
        ],
      },
      {
        id: "202",
        name: "Women's Clothing",
        slug: "womens-clothing",
        categoryId: "2",
        subCategory: [
          { id: "2021", name: "Dresses", slug: "dresses", categoryId: "202" },
          { id: "2022", name: "Shirts", slug: "shirts", categoryId: "202" },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    subCategory: [
      {
        id: "301",
        name: "Furniture",
        slug: "furniture",
        categoryId: "3",
        subCategory: [
          {
            id: "3011",
            name: "Living Room",
            slug: "living-room",
            categoryId: "301",
          },
          { id: "3012", name: "Bedroom", slug: "bedroom", categoryId: "301" },
        ],
      },
      {
        id: "302",
        name: "Appliances",
        slug: "appliances",
        categoryId: "3",
        subCategory: [
          {
            id: "3021",
            name: "Kitchen Appliances",
            slug: "kitchen-appliances",
            categoryId: "302",
          },
          {
            id: "3022",
            name: "Cleaning Appliances",
            slug: "cleaning-appliances",
            categoryId: "302",
          },
        ],
      },
    ],
  },
  {
    id: "4",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    subCategory: [
      {
        id: "401",
        name: "Fitness",
        slug: "fitness",
        categoryId: "4",
        subCategory: [
          {
            id: "4011",
            name: "Equipment",
            slug: "equipment",
            categoryId: "401",
          },
          { id: "4012", name: "Clothing", slug: "clothing", categoryId: "401" },
        ],
      },
      {
        id: "402",
        name: "Outdoor Recreation",
        slug: "outdoor-recreation",
        categoryId: "4",
        subCategory: [
          { id: "4021", name: "Camping", slug: "camping", categoryId: "402" },
          { id: "4022", name: "Hiking", slug: "hiking", categoryId: "402" },
        ],
      },
    ],
  },
  {
    id: "5",
    name: "Beauty & Health",
    slug: "beauty-health",
    subCategory: [
      {
        id: "501",
        name: "Skincare",
        slug: "skincare",
        categoryId: "5",
        subCategory: [
          { id: "5011", name: "Face", slug: "face", categoryId: "501" },
          { id: "5012", name: "Body", slug: "body", categoryId: "501" },
        ],
      },
      {
        id: "502",
        name: "Hair Care",
        slug: "hair-care",
        categoryId: "5",
        subCategory: [
          {
            id: "5021",
            name: "Shampoo & Conditioner",
            slug: "shampoo-conditioner",
            categoryId: "502",
          },
          {
            id: "5022",
            name: "Styling Products",
            slug: "styling-products",
            categoryId: "502",
          },
        ],
      },
    ],
  },
];

export const products = [
  {
    id: "p1",
    name: "iPhone 15 Pro",
    slug: "iphone-15-pro",
    description: "The latest iPhone with A17 Bionic chip.",
    details: [
      "6.1-inch Super Retina XDR display",
      "A17 Bionic chip",
      "Triple-lens camera system",
      "Titanium frame",
    ],
    brand: "Apple",
    price: 1099.99,
    discount: 10.0,
    finalPrice: 989.99,
    stock: 20,
    categoryId: "1", // Assuming this matches an existing category
    images: ["/images/iphone-15-pro.webp"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: true,
  },
  {
    id: "p2",
    name: "Samsung Galaxy S24 Ultra",
    slug: "samsung-galaxy-s24-ultra",
    description: "Powerful smartphone with an advanced camera system.",
    details: [
      "6.8-inch Dynamic AMOLED 2X",
      "Snapdragon 8 Gen 3",
      "200MP camera",
      "S Pen included",
    ],
    brand: "Samsung",
    price: 1299.99,
    discount: 15.0,
    finalPrice: 1104.99,
    stock: 15,
    categoryId: "1",
    images: ["/images/samsung-galaxy-s24-ultra.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: true,
  },
  {
    id: "p3",
    name: "MacBook Pro 16",
    slug: "macbook-pro-16",
    description: "Powerful laptop for professionals with M2 Pro chip.",
    details: [
      "16-inch Liquid Retina XDR display",
      "Apple M2 Pro chip",
      "32GB unified memory",
      "1TB SSD storage",
    ],
    brand: "Apple",
    price: 2499.99,
    discount: 5.0,
    finalPrice: 2374.99,
    stock: 10,
    categoryId: "2",
    images: ["/images/samsung-galaxy-s24-ultra.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: true,
  },
  {
    id: "p4",
    name: "Sony WH-1000XM5",
    slug: "sony-wh-1000xm5",
    description: "Premium noise-cancelling headphones with exceptional sound.",
    details: [
      "Industry-leading noise cancellation",
      "30-hour battery life",
      "High-resolution audio",
      "Comfortable design",
    ],
    brand: "Sony",
    price: 399.99,
    discount: 0,
    finalPrice: 399.99,
    stock: 25,
    categoryId: "3",
    images: ["/images/samsung-galaxy-s24-ultra.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: true,
  },
  {
    id: "p5",
    name: "iPad Pro 12.9",
    slug: "ipad-pro-12-9",
    description:
      "The ultimate iPad experience with M2 chip and stunning display.",
    details: [
      "12.9-inch Liquid Retina XDR display",
      "Apple M2 chip",
      "Thunderbolt / USB 4 port",
      "Face ID",
    ],
    brand: "Apple",
    price: 1099.99,
    discount: 8.0,
    finalPrice: 1011.99,
    stock: 18,
    categoryId: "4",
    images: ["/images/samsung-galaxy-s24-ultra.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: true,
  },
  {
    id: "p6",
    name: "PlayStation 5",
    slug: "playstation-5",
    description: "Next-gen gaming console with lightning-fast loading times.",
    details: [
      "AMD Zen 2 CPU",
      "Custom RDNA 2 GPU",
      "825GB SSD storage",
      "4K gaming at 120fps",
    ],
    brand: "Sony",
    price: 499.99,
    discount: 0,
    finalPrice: 499.99,
    stock: 8,
    categoryId: "5",
    images: ["/images/samsung-galaxy-s24-ultra.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: true,
  },
  {
    id: "p7",
    name: "Apple Watch Series 9",
    slug: "apple-watch-series-9",
    description:
      "Advanced health monitoring and connectivity in a sleek design.",
    details: [
      "Always-On Retina display",
      "Blood oxygen & ECG apps",
      "Water resistant to 50m",
      "18-hour battery life",
    ],
    brand: "Apple",
    price: 399.99,
    discount: 5.0,
    finalPrice: 379.99,
    stock: 22,
    categoryId: "6",
    images: ["/images/samsung-galaxy-s24-ultra.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: true,
  },
  {
    id: "p8",
    name: "Canon EOS R6 Mark II",
    slug: "canon-eos-r6-mark-ii",
    description:
      "Professional mirrorless camera with exceptional low-light performance.",
    details: [
      "24.2MP full-frame CMOS sensor",
      "In-body image stabilization",
      "4K60p video recording",
      "40fps continuous shooting",
    ],
    brand: "Canon",
    price: 2499.99,
    discount: 12.0,
    finalPrice: 2199.99,
    stock: 7,
    categoryId: "7",
    images: ["/images/samsung-galaxy-s24-ultra.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: true,
  },
  {
    id: "p9",
    name: "ASUS ROG Strix G17",
    slug: "asus-rog-strix-g17",
    description: "High-performance gaming laptop with RGB lighting.",
    details: [
      "17.3-inch 300Hz FHD display",
      "AMD Ryzen 9 processor",
      "NVIDIA RTX 3080 graphics",
      "1TB NVMe SSD",
    ],
    brand: "ASUS",
    price: 1999.99,
    discount: 7.0,
    finalPrice: 1859.99,
    stock: 12,
    categoryId: "1021", // Gaming Laptops category
    images: ["/images/asus-rog-strix.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: false,
  },
  {
    id: "p10",
    name: "LG OLED C3 65-inch TV",
    slug: "lg-oled-c3-65",
    description: "Premium OLED TV with stunning picture quality.",
    details: [
      "65-inch 4K OLED display",
      "a9 Gen6 AI Processor",
      "Dolby Vision & Atmos support",
      "Game Optimizer mode",
    ],
    brand: "LG",
    price: 2499.99,
    discount: 10.0,
    finalPrice: 2249.99,
    stock: 9,
    categoryId: "1", // Electronics category
    images: ["/images/lg-oled-tv.jpg"],
    createdAt: new Date(),
    updatedAt: new Date(),
    offerId: null,
    wishList: [],
    CartItem: [],
    isFeatured: false,
  },
];
